### ISSUE TITLE
[43.03] exportlegends sites errors out after ~1000 site maps

### ISSUE THREAD

**Issue by sparkybear** [DFHack/dfhack#958]
This error has occurred every time I've tried to do an exportlegends sites on both Linux, and Windows (7,8.1, 10). It will always occur on a world with more than a couple hundred site maps.

I've attached an image of the error thrown.
http://imgur.com/qKJQURI

No progress is displayed on screen during the sites exports, and I've noticed it usually errors out after 1000-1200 site maps have been exported.

**Comment by lethosor** [comment]
I haven't seen that error message before, but several issues with exportlegends have been fixed since that version.

**Comment by sparkybear** [comment]
The issue has occurred for me since the initial 40.xx versions onward, I didn't play prior to that. I tried playing around with the scripts yesterday, thinking it could be some issue with needing to flush out the stream that outputs the file, but my knowledge of Lua is limited and didn't have much luck. Other than that, I have no idea what the cause could be.

**Comment by lethosor** [comment]
You're getting a nil error message, which shouldn't be possible, looking at screen_doSimulateInput in LuaApi.cpp, and I can't say I've ever seen it. Does it really occur with any world, or have you been using the same world(s)? Any idea on the number of sites in some of the world(s) with the issue?

**Comment by sparkybear** [comment]
It happens any time I generate a world with more than 1000 sites or so, though that's not a guarantee. I've had it error out after exporting 2 sites or 10 sites, though usually it'll make it to a little over 1000. Dozens of different worlds over the last year have all given the same errors. I generated 2 new worlds in the last week and it occurred with both.

**Comment by sparkybear** [comment]
Issue still occurs with a new world on 43.03

http://i.imgur.com/RzkStnU.png

**Comment by lethosor** [comment]
How are you checking how far it's getting?

**Comment by sparkybear** [comment]
I can see the exported maps in the Dwarf Fortress Folder. Each is numbered, sorting by name it'll go from "xxxxx-xxx-xxx-01" all the way up to the last one that is exported before the error occurs.

**Comment by lethosor** [comment]
Are you doing this in normal legends mode or with open-legends?

**Comment by sparkybear** [comment]
Always in normal legends mode.

**Comment by lethosor** [comment]
I tried with a save that has 933 sites listed in world_data.sites but just ends up exporting 529 maps, and didn't have any luck reproducing it.

Here's something you could try, I guess - in hack/lua/gui.lua, before the line that reads `dscreen._doSimulateInput(screen, keys)`, add:
```lua
print(screen)
printall(keys)
```
and see what shows up right before the error message.

Also, you can copy and paste from the console on Windows by right-clicking the title bar. It'll let you include more than one page, and we usually prefer it to screenshots.

**Comment by sparkybear** [comment]
Sure thing. Another note. If I try to run the exportlegends sites from the main, normal legends screen, without removing the already exported .bmp files, it will error out almost immediately. I would have included the output from that instance as well, but it's identical.

Here you are:

`<viewscreen_legendsst: 0x380ca418>
1                        = 238
<viewscreen_legendsst: 0x380ca418>
1                        = 28
<viewscreen_legendsst: 0x380ca418>
1                        = 238
<viewscreen_legendsst: 0x380ca418>
1                        = 28
<viewscreen_legendsst: 0x380ca418>
1                        = 238
<viewscreen_legendsst: 0x380ca418>
1                        = 28
<viewscreen_legendsst: 0x380ca418>
1                        = 238
<viewscreen_legendsst: 0x380ca418>
1                        = 28
nil
stack traceback:
        [C]: in function '_doSimulateInput'
        D:\PERIDE~1\Dwarf Fortress 0.43.03\hack\lua\gui.lua:52: in function 'sim
ulateInput'
        ...~1\Dwarf Fortress 0.43.03/hack/scripts/exportlegends.lua:808: in func
tion 'export_site_maps'
        ...~1\Dwarf Fortress 0.43.03/hack/scripts/exportlegends.lua:828: in func
tion 'f'
        D:\PERIDE~1\Dwarf Fortress 0.43.03\hack\lua\dfhack.lua:562: in function
<D:\PERIDE~1\Dwarf Fortress 0.43.03\hack\lua\dfhack.lua:503>
        (...tail calls...)
[DFHack]#`

**Comment by lethosor** [comment]
It's not doing that for me, strangely. If you remove all the maps and create 1000+ empty/useless files in the DF folder, do you get the same issue?

**Comment by sparkybear** [comment]
Not really,I just did a few tests with this to try and narrow it down a little. I don't know if it helps but:

1. Export sites without dummy files - errors after about 1000 sites as usual.
2. Clear out exported sites. Revert to main legends screen.
3. Add 1200 empty dummy files.
4. Export sites errors out almost immediately.
5. Remove exported sites, but keep dummy files.
6. Restart DFHack
7. Re-run export sites, errors out after about 1000 sites. 
8. Don't clear out the sites or dummy files.
9. Re-run export sites, errors out almost immediately.
10. Clear both sites and dummy files.
11. Re-run export sites, without restarting dfhack, errors out almost immediately
12. Restart dfhack
13. Clear out and re-run, errors out after ~1000 sites again

**Comment by lethosor** [comment]
What filesystem are you using? (I couldn't find references to any common ones with file-per-directory limits that low, but I can't think of much else.)

**Comment by sparkybear** [comment]
NTFS. 

My only other idea would be if the script is trying to write to a file that is being written to by another part of the function? Though that really doesn't make sense in this case.

**Comment by lethosor** [comment]
You said this happens on Linux too - is that running in a VM, natively on the same computer, or on a different machine?

Can you try making a macro that runs in the sites list and exports each site map, and run it repeatedly with MACRO_MS:0? It'll only let you repeat the macro 99 times, so either make it consist of the key sequence several times or run it in a situation where it tends to fail quickly, I guess.

**Comment by sparkybear** [comment]
Sure thing, I'll get back to you once it's finished. I'll also run a similar macro on the Windows partition. Linux is run natively on the same machine, EXT4 file system.

**Comment by lethosor** [comment]
I'm not great at deciphering that, but the fact that the macro makes DF crash confirms my suspicion that some error is occurring that gets caught by some layer of DFHack's Lua API. I don't think it's a C++ exception, since that would result in at least "C++ exception" as part of the error message. I would say that this should be reported on the bugtracker if you can reproduce it without DFHack (since DFHack doesn't interfere with macros, I'd say there's a good chance you can).

@ragundo: I'm wondering if this is related to the "exportmaps sites" crash.

**Comment by sparkybear** [comment]
Well. I figured it out. It's a memory issue. Making Dwarf Fortress large address aware totally fixed the problem with both the script and the macro. When DF is exporting sites to a file, the sites are loaded into memory, but not flushed from memory until after exiting legends mode. As for why DFHack is erroring out while running the Lua script, I have no idea.

**Comment by lethosor** [comment]
Oh, that makes sense. If a memory allocation fails under the Lua API, you usually see an "out of memory" error message. It's strange that there wasn't a message this time, but I think that explains it.

**Comment by sparkybear** [comment]
Yeah. I guess what I'm confused about still is that when the script errored out, DF and DFHack continued to run fine without crashing, but DF was close to the ~2GB memory limit. The crash occurred solely with the macro where DF could hit that memory limit.

I'm not sure this is the case or not, but it seemed the Lua API halted the script before an out of memory exception would occur. Anyway, problem seems to be solved. I can think of a few ways to work around the limitation if there's demand for it, but it doesn't look like it'll be a problem following the x64 release.

**Comment by lethosor** [comment]
I'm pretty sure the Lua API caught the memory error somehow, but just wasn't indicating it properly.

Yeah, this shouldn't be an issue on x64 (it's getting DFHack to work there that's the harder part :) )

**Comment by sparkybear** [comment]
I can only imagine. Thanks for your time

**Comment by sparkybear** [comment]
So, this has re-appeared in 43.05. Not a memory issue. Just seems to be a hard limit on 1500 sites total being exported, followed by DF becoming unresponsive. I'm not sure if this is related to another export issue or not, so I didn't want to re-open it for the time being.

**Comment by lethosor** [comment]
@sparkybear 64-bit DF? 

I just fixed #1017 - I don't think this is exactly the same issue, but maybe it's related. You could try the fixed script from there and see if it helps.

**Comment by sparkybear** [comment]
Yea, 64bit with the latest DFHack. I'll try out the new script and see if that makes a difference.

**Comment by lethosor** [comment]
Actually, I don't think it would, because it also relies on a structure fix. Sorry about that. Maybe you could try in r2 when it's out and see if it works there.

**Comment by sparkybear** [comment]
No worries, I don't mind waiting, thanks for checking in.
